#----------------------------------
#           BeeHivesTrees
#
#           By: Esmorall
#
#----------------------------------

#Chance from 0.0 to 1.0, 1 = 100%
chance-to-have-a-bee-nest: 0.05

#Do you want to allow trees with bees if using bone meal?
allow-bonemeal: false

#How many bees per tree with nest
min-bees-per-nest: 1
max-bees-per-nest: 3

#enabling this option will allow all biome ignoring the list below
allow-all-biomes: false

#Use names from this list https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html
allowed-biomes:
  - FOREST
  - PLAINS
  - FLOWER_FOREST
  - SUNFLOWER_PLAINS
  - BIRCH_FOREST
  - BIRCH_FOREST_HILLS
  - TALL_BIRCH_FOREST
  - TALL_BIRCH_HILLS
  
#enabling this option will allow all tree types ignoring the list below
allow-all-tree-types: false

#Use names from this list https://hub.spigotmc.org/javadocs/spigot/org/bukkit/TreeType.html
allowed-tree-types:
  - TREE
  - BIG_TREE
  - BIRCH
  - TALL_BIRCH