name: BeeHivesTrees
main: net.minemora.beehivestrees.BeeHivesTrees
version: 1.2
api-version: 1.15
author: Esmorall
description: Add a chance to spawn a beehive when a tree grows from a sapling.
commands: